version: "3.4"

services:
  database:
    image: percona:8.0.29-21
    cap_add:
      - SYS_NICE # https://stackoverflow.com/a/55706057/7105287
    environment:
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - ./db:/var/lib/mysql
